/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as AuthenticatedImport } from "./routes/_authenticated"
import { Route as IndexImport } from "./routes/index"
import { Route as AuthSendVerificationEmailImport } from "./routes/auth/send-verification-email"
import { Route as AuthResetPasswordImport } from "./routes/auth/reset-password"
import { Route as AuthRegisterImport } from "./routes/auth/register"
import { Route as AuthLoginImport } from "./routes/auth/login"
import { Route as AuthForgotPasswordImport } from "./routes/auth/forgot-password"
import { Route as AuthAccountCreatedImport } from "./routes/auth/account-created"
import { Route as AuthLayoutImport } from "./routes/auth/_layout"
import { Route as AuthVerifyIndexImport } from "./routes/auth/verify/index"
import { Route as AuthenticatedDashboardIndexImport } from "./routes/_authenticated/dashboard/index"
import { Route as AuthVerifyVerifyImport } from "./routes/auth/verify/_verify"
import { Route as AuthenticatedUserUserImport } from "./routes/_authenticated/user/_user"
import { Route as AuthenticatedDashboardSocialImport } from "./routes/_authenticated/dashboard/social"
import { Route as AuthenticatedDashboardMembersImport } from "./routes/_authenticated/dashboard/members"
import { Route as AuthenticatedDashboardActivitiesImport } from "./routes/_authenticated/dashboard/activities"
import { Route as AuthenticatedFacilitiesRoomsIndexImport } from "./routes/_authenticated/facilities/rooms/index"
import { Route as AuthenticatedFacilitiesComplexesIndexImport } from "./routes/_authenticated/facilities/complexes/index"
import { Route as AuthenticatedDashboardClubsIndexImport } from "./routes/_authenticated/dashboard/clubs/index"
import { Route as AuthVerifyVerifySuccessImport } from "./routes/auth/verify/_verify.success"
import { Route as AuthVerifyVerifyErrorImport } from "./routes/auth/verify/_verify.error"
import { Route as AuthenticatedUserUserSettingsImport } from "./routes/_authenticated/user/_user.settings"
import { Route as AuthenticatedUserUserProfileImport } from "./routes/_authenticated/user/_user.profile"
import { Route as AuthenticatedFacilitiesComplexesCreateImport } from "./routes/_authenticated/facilities/complexes/create"
import { Route as AuthenticatedDashboardClubsCreateImport } from "./routes/_authenticated/dashboard/clubs/create"
import { Route as AuthenticatedFacilitiesRoomsRoomIdIndexImport } from "./routes/_authenticated/facilities/rooms/$roomId/index"
import { Route as AuthenticatedFacilitiesComplexesComplexIdIndexImport } from "./routes/_authenticated/facilities/complexes/$complexId/index"
import { Route as AuthenticatedDashboardClubsClubIdIndexImport } from "./routes/_authenticated/dashboard/clubs/$clubId/index"
import { Route as AuthenticatedFacilitiesRoomsRoomIdEditImport } from "./routes/_authenticated/facilities/rooms/$roomId.edit"
import { Route as AuthenticatedFacilitiesComplexesComplexIdEditImport } from "./routes/_authenticated/facilities/complexes/$complexId.edit"
import { Route as AuthenticatedFacilitiesComplexesComplexIdCreateRoomImport } from "./routes/_authenticated/facilities/complexes/$complexId.create-room"
import { Route as AuthenticatedDashboardClubsClubIdEditImport } from "./routes/_authenticated/dashboard/clubs/$clubId/edit"
import { Route as AuthenticatedDashboardClubsClubIdSessionsIndexImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sessions/index"
import { Route as AuthenticatedDashboardClubsClubIdSectionsIndexImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sections/index"
import { Route as AuthenticatedDashboardClubsClubIdCategoriesIndexImport } from "./routes/_authenticated/dashboard/clubs/$clubId/categories/index"
import { Route as AuthenticatedDashboardClubsClubIdSectionsCreateImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sections/create"
import { Route as AuthenticatedDashboardClubsClubIdSectionsSectionIdIndexImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/index"
import { Route as AuthenticatedDashboardClubsClubIdSectionsSectionIdEditImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/edit"
import { Route as AuthenticatedDashboardClubsClubIdSectionsSectionIdSessionsIndexImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/sessions/index"
import { Route as AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesIndexImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/index"
import { Route as AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCreateImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/create"
import { Route as AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdEditImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit"
import { Route as AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsIndexImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/index"
import { Route as AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsCreateImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create"
import { Route as AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsSessionIdEditImport } from "./routes/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit"

// Create Virtual Routes

const AuthImport = createFileRoute("/auth")()
const AuthVerifyImport = createFileRoute("/auth/verify")()
const AuthenticatedUserImport = createFileRoute("/_authenticated/user")()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyRoute = AuthVerifyImport.update({
  id: "/verify",
  path: "/verify",
  getParentRoute: () => AuthRoute,
} as any)

const AuthenticatedUserRoute = AuthenticatedUserImport.update({
  id: "/user",
  path: "/user",
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthSendVerificationEmailRoute = AuthSendVerificationEmailImport.update({
  id: "/send-verification-email",
  path: "/send-verification-email",
  getParentRoute: () => AuthRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRoute,
} as any)

const AuthAccountCreatedRoute = AuthAccountCreatedImport.update({
  id: "/account-created",
  path: "/account-created",
  getParentRoute: () => AuthRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: "/_layout",
  getParentRoute: () => AuthRoute,
} as any)

const AuthVerifyIndexRoute = AuthVerifyIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthVerifyRoute,
} as any)

const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexImport.update({
    id: "/dashboard/",
    path: "/dashboard/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthVerifyVerifyRoute = AuthVerifyVerifyImport.update({
  id: "/_verify",
  getParentRoute: () => AuthVerifyRoute,
} as any)

const AuthenticatedUserUserRoute = AuthenticatedUserUserImport.update({
  id: "/_user",
  getParentRoute: () => AuthenticatedUserRoute,
} as any)

const AuthenticatedDashboardSocialRoute =
  AuthenticatedDashboardSocialImport.update({
    id: "/dashboard/social",
    path: "/dashboard/social",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardMembersRoute =
  AuthenticatedDashboardMembersImport.update({
    id: "/dashboard/members",
    path: "/dashboard/members",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardActivitiesRoute =
  AuthenticatedDashboardActivitiesImport.update({
    id: "/dashboard/activities",
    path: "/dashboard/activities",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedFacilitiesRoomsIndexRoute =
  AuthenticatedFacilitiesRoomsIndexImport.update({
    id: "/facilities/rooms/",
    path: "/facilities/rooms/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedFacilitiesComplexesIndexRoute =
  AuthenticatedFacilitiesComplexesIndexImport.update({
    id: "/facilities/complexes/",
    path: "/facilities/complexes/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsIndexRoute =
  AuthenticatedDashboardClubsIndexImport.update({
    id: "/dashboard/clubs/",
    path: "/dashboard/clubs/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthVerifyVerifySuccessRoute = AuthVerifyVerifySuccessImport.update({
  id: "/success",
  path: "/success",
  getParentRoute: () => AuthVerifyVerifyRoute,
} as any)

const AuthVerifyVerifyErrorRoute = AuthVerifyVerifyErrorImport.update({
  id: "/error",
  path: "/error",
  getParentRoute: () => AuthVerifyVerifyRoute,
} as any)

const AuthenticatedUserUserSettingsRoute =
  AuthenticatedUserUserSettingsImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => AuthenticatedUserUserRoute,
  } as any)

const AuthenticatedUserUserProfileRoute =
  AuthenticatedUserUserProfileImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => AuthenticatedUserUserRoute,
  } as any)

const AuthenticatedFacilitiesComplexesCreateRoute =
  AuthenticatedFacilitiesComplexesCreateImport.update({
    id: "/facilities/complexes/create",
    path: "/facilities/complexes/create",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsCreateRoute =
  AuthenticatedDashboardClubsCreateImport.update({
    id: "/dashboard/clubs/create",
    path: "/dashboard/clubs/create",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedFacilitiesRoomsRoomIdIndexRoute =
  AuthenticatedFacilitiesRoomsRoomIdIndexImport.update({
    id: "/facilities/rooms/$roomId/",
    path: "/facilities/rooms/$roomId/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedFacilitiesComplexesComplexIdIndexRoute =
  AuthenticatedFacilitiesComplexesComplexIdIndexImport.update({
    id: "/facilities/complexes/$complexId/",
    path: "/facilities/complexes/$complexId/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsClubIdIndexRoute =
  AuthenticatedDashboardClubsClubIdIndexImport.update({
    id: "/dashboard/clubs/$clubId/",
    path: "/dashboard/clubs/$clubId/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedFacilitiesRoomsRoomIdEditRoute =
  AuthenticatedFacilitiesRoomsRoomIdEditImport.update({
    id: "/facilities/rooms/$roomId/edit",
    path: "/facilities/rooms/$roomId/edit",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedFacilitiesComplexesComplexIdEditRoute =
  AuthenticatedFacilitiesComplexesComplexIdEditImport.update({
    id: "/facilities/complexes/$complexId/edit",
    path: "/facilities/complexes/$complexId/edit",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedFacilitiesComplexesComplexIdCreateRoomRoute =
  AuthenticatedFacilitiesComplexesComplexIdCreateRoomImport.update({
    id: "/facilities/complexes/$complexId/create-room",
    path: "/facilities/complexes/$complexId/create-room",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsClubIdEditRoute =
  AuthenticatedDashboardClubsClubIdEditImport.update({
    id: "/dashboard/clubs/$clubId/edit",
    path: "/dashboard/clubs/$clubId/edit",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsClubIdSessionsIndexRoute =
  AuthenticatedDashboardClubsClubIdSessionsIndexImport.update({
    id: "/dashboard/clubs/$clubId/sessions/",
    path: "/dashboard/clubs/$clubId/sessions/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsClubIdSectionsIndexRoute =
  AuthenticatedDashboardClubsClubIdSectionsIndexImport.update({
    id: "/dashboard/clubs/$clubId/sections/",
    path: "/dashboard/clubs/$clubId/sections/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsClubIdCategoriesIndexRoute =
  AuthenticatedDashboardClubsClubIdCategoriesIndexImport.update({
    id: "/dashboard/clubs/$clubId/categories/",
    path: "/dashboard/clubs/$clubId/categories/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsClubIdSectionsCreateRoute =
  AuthenticatedDashboardClubsClubIdSectionsCreateImport.update({
    id: "/dashboard/clubs/$clubId/sections/create",
    path: "/dashboard/clubs/$clubId/sections/create",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsClubIdSectionsSectionIdIndexRoute =
  AuthenticatedDashboardClubsClubIdSectionsSectionIdIndexImport.update({
    id: "/dashboard/clubs/$clubId/sections/$sectionId/",
    path: "/dashboard/clubs/$clubId/sections/$sectionId/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsClubIdSectionsSectionIdEditRoute =
  AuthenticatedDashboardClubsClubIdSectionsSectionIdEditImport.update({
    id: "/dashboard/clubs/$clubId/sections/$sectionId/edit",
    path: "/dashboard/clubs/$clubId/sections/$sectionId/edit",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsClubIdSectionsSectionIdSessionsIndexRoute =
  AuthenticatedDashboardClubsClubIdSectionsSectionIdSessionsIndexImport.update({
    id: "/dashboard/clubs/$clubId/sections/$sectionId/sessions/",
    path: "/dashboard/clubs/$clubId/sections/$sectionId/sessions/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesIndexRoute =
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesIndexImport.update(
    {
      id: "/dashboard/clubs/$clubId/sections/$sectionId/categories/",
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories/",
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

const AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCreateRoute =
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCreateImport.update(
    {
      id: "/dashboard/clubs/$clubId/sections/$sectionId/categories/create",
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories/create",
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

const AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdEditRoute =
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdEditImport.update(
    {
      id: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit",
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit",
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

const AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsIndexRoute =
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsIndexImport.update(
    {
      id: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/",
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/",
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

const AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsCreateRoute =
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsCreateImport.update(
    {
      id: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create",
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create",
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

const AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsSessionIdEditRoute =
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsSessionIdEditImport.update(
    {
      id: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit",
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit",
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    "/auth/_layout": {
      id: "/auth/_layout"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    "/auth/account-created": {
      id: "/auth/account-created"
      path: "/account-created"
      fullPath: "/auth/account-created"
      preLoaderRoute: typeof AuthAccountCreatedImport
      parentRoute: typeof AuthImport
    }
    "/auth/forgot-password": {
      id: "/auth/forgot-password"
      path: "/forgot-password"
      fullPath: "/auth/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    "/auth/login": {
      id: "/auth/login"
      path: "/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    "/auth/register": {
      id: "/auth/register"
      path: "/register"
      fullPath: "/auth/register"
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    "/auth/reset-password": {
      id: "/auth/reset-password"
      path: "/reset-password"
      fullPath: "/auth/reset-password"
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof AuthImport
    }
    "/auth/send-verification-email": {
      id: "/auth/send-verification-email"
      path: "/send-verification-email"
      fullPath: "/auth/send-verification-email"
      preLoaderRoute: typeof AuthSendVerificationEmailImport
      parentRoute: typeof AuthImport
    }
    "/_authenticated/dashboard/activities": {
      id: "/_authenticated/dashboard/activities"
      path: "/dashboard/activities"
      fullPath: "/dashboard/activities"
      preLoaderRoute: typeof AuthenticatedDashboardActivitiesImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/members": {
      id: "/_authenticated/dashboard/members"
      path: "/dashboard/members"
      fullPath: "/dashboard/members"
      preLoaderRoute: typeof AuthenticatedDashboardMembersImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/social": {
      id: "/_authenticated/dashboard/social"
      path: "/dashboard/social"
      fullPath: "/dashboard/social"
      preLoaderRoute: typeof AuthenticatedDashboardSocialImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/user": {
      id: "/_authenticated/user"
      path: "/user"
      fullPath: "/user"
      preLoaderRoute: typeof AuthenticatedUserImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/user/_user": {
      id: "/_authenticated/user/_user"
      path: "/user"
      fullPath: "/user"
      preLoaderRoute: typeof AuthenticatedUserUserImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    "/auth/verify": {
      id: "/auth/verify"
      path: "/verify"
      fullPath: "/auth/verify"
      preLoaderRoute: typeof AuthVerifyImport
      parentRoute: typeof AuthImport
    }
    "/auth/verify/_verify": {
      id: "/auth/verify/_verify"
      path: "/verify"
      fullPath: "/auth/verify"
      preLoaderRoute: typeof AuthVerifyVerifyImport
      parentRoute: typeof AuthVerifyRoute
    }
    "/_authenticated/dashboard/": {
      id: "/_authenticated/dashboard/"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AuthenticatedDashboardIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/auth/verify/": {
      id: "/auth/verify/"
      path: "/"
      fullPath: "/auth/verify/"
      preLoaderRoute: typeof AuthVerifyIndexImport
      parentRoute: typeof AuthVerifyImport
    }
    "/_authenticated/dashboard/clubs/create": {
      id: "/_authenticated/dashboard/clubs/create"
      path: "/dashboard/clubs/create"
      fullPath: "/dashboard/clubs/create"
      preLoaderRoute: typeof AuthenticatedDashboardClubsCreateImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/facilities/complexes/create": {
      id: "/_authenticated/facilities/complexes/create"
      path: "/facilities/complexes/create"
      fullPath: "/facilities/complexes/create"
      preLoaderRoute: typeof AuthenticatedFacilitiesComplexesCreateImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/user/_user/profile": {
      id: "/_authenticated/user/_user/profile"
      path: "/profile"
      fullPath: "/user/profile"
      preLoaderRoute: typeof AuthenticatedUserUserProfileImport
      parentRoute: typeof AuthenticatedUserUserImport
    }
    "/_authenticated/user/_user/settings": {
      id: "/_authenticated/user/_user/settings"
      path: "/settings"
      fullPath: "/user/settings"
      preLoaderRoute: typeof AuthenticatedUserUserSettingsImport
      parentRoute: typeof AuthenticatedUserUserImport
    }
    "/auth/verify/_verify/error": {
      id: "/auth/verify/_verify/error"
      path: "/error"
      fullPath: "/auth/verify/error"
      preLoaderRoute: typeof AuthVerifyVerifyErrorImport
      parentRoute: typeof AuthVerifyVerifyImport
    }
    "/auth/verify/_verify/success": {
      id: "/auth/verify/_verify/success"
      path: "/success"
      fullPath: "/auth/verify/success"
      preLoaderRoute: typeof AuthVerifyVerifySuccessImport
      parentRoute: typeof AuthVerifyVerifyImport
    }
    "/_authenticated/dashboard/clubs/": {
      id: "/_authenticated/dashboard/clubs/"
      path: "/dashboard/clubs"
      fullPath: "/dashboard/clubs"
      preLoaderRoute: typeof AuthenticatedDashboardClubsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/facilities/complexes/": {
      id: "/_authenticated/facilities/complexes/"
      path: "/facilities/complexes"
      fullPath: "/facilities/complexes"
      preLoaderRoute: typeof AuthenticatedFacilitiesComplexesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/facilities/rooms/": {
      id: "/_authenticated/facilities/rooms/"
      path: "/facilities/rooms"
      fullPath: "/facilities/rooms"
      preLoaderRoute: typeof AuthenticatedFacilitiesRoomsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/edit": {
      id: "/_authenticated/dashboard/clubs/$clubId/edit"
      path: "/dashboard/clubs/$clubId/edit"
      fullPath: "/dashboard/clubs/$clubId/edit"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/facilities/complexes/$complexId/create-room": {
      id: "/_authenticated/facilities/complexes/$complexId/create-room"
      path: "/facilities/complexes/$complexId/create-room"
      fullPath: "/facilities/complexes/$complexId/create-room"
      preLoaderRoute: typeof AuthenticatedFacilitiesComplexesComplexIdCreateRoomImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/facilities/complexes/$complexId/edit": {
      id: "/_authenticated/facilities/complexes/$complexId/edit"
      path: "/facilities/complexes/$complexId/edit"
      fullPath: "/facilities/complexes/$complexId/edit"
      preLoaderRoute: typeof AuthenticatedFacilitiesComplexesComplexIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/facilities/rooms/$roomId/edit": {
      id: "/_authenticated/facilities/rooms/$roomId/edit"
      path: "/facilities/rooms/$roomId/edit"
      fullPath: "/facilities/rooms/$roomId/edit"
      preLoaderRoute: typeof AuthenticatedFacilitiesRoomsRoomIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/": {
      id: "/_authenticated/dashboard/clubs/$clubId/"
      path: "/dashboard/clubs/$clubId"
      fullPath: "/dashboard/clubs/$clubId"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/facilities/complexes/$complexId/": {
      id: "/_authenticated/facilities/complexes/$complexId/"
      path: "/facilities/complexes/$complexId"
      fullPath: "/facilities/complexes/$complexId"
      preLoaderRoute: typeof AuthenticatedFacilitiesComplexesComplexIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/facilities/rooms/$roomId/": {
      id: "/_authenticated/facilities/rooms/$roomId/"
      path: "/facilities/rooms/$roomId"
      fullPath: "/facilities/rooms/$roomId"
      preLoaderRoute: typeof AuthenticatedFacilitiesRoomsRoomIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sections/create": {
      id: "/_authenticated/dashboard/clubs/$clubId/sections/create"
      path: "/dashboard/clubs/$clubId/sections/create"
      fullPath: "/dashboard/clubs/$clubId/sections/create"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSectionsCreateImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/categories/": {
      id: "/_authenticated/dashboard/clubs/$clubId/categories/"
      path: "/dashboard/clubs/$clubId/categories"
      fullPath: "/dashboard/clubs/$clubId/categories"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdCategoriesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sections/": {
      id: "/_authenticated/dashboard/clubs/$clubId/sections/"
      path: "/dashboard/clubs/$clubId/sections"
      fullPath: "/dashboard/clubs/$clubId/sections"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSectionsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sessions/": {
      id: "/_authenticated/dashboard/clubs/$clubId/sessions/"
      path: "/dashboard/clubs/$clubId/sessions"
      fullPath: "/dashboard/clubs/$clubId/sessions"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSessionsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/edit": {
      id: "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/edit"
      path: "/dashboard/clubs/$clubId/sections/$sectionId/edit"
      fullPath: "/dashboard/clubs/$clubId/sections/$sectionId/edit"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/": {
      id: "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/"
      path: "/dashboard/clubs/$clubId/sections/$sectionId"
      fullPath: "/dashboard/clubs/$clubId/sections/$sectionId"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/create": {
      id: "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/create"
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories/create"
      fullPath: "/dashboard/clubs/$clubId/sections/$sectionId/categories/create"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCreateImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/": {
      id: "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/"
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories"
      fullPath: "/dashboard/clubs/$clubId/sections/$sectionId/categories"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/sessions/": {
      id: "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/sessions/"
      path: "/dashboard/clubs/$clubId/sections/$sectionId/sessions"
      fullPath: "/dashboard/clubs/$clubId/sections/$sectionId/sessions"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdSessionsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit": {
      id: "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit"
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit"
      fullPath: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create": {
      id: "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create"
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create"
      fullPath: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsCreateImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/": {
      id: "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/"
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions"
      fullPath: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit": {
      id: "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit"
      path: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit"
      fullPath: "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit"
      preLoaderRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsSessionIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedUserUserRouteChildren {
  AuthenticatedUserUserProfileRoute: typeof AuthenticatedUserUserProfileRoute
  AuthenticatedUserUserSettingsRoute: typeof AuthenticatedUserUserSettingsRoute
}

const AuthenticatedUserUserRouteChildren: AuthenticatedUserUserRouteChildren = {
  AuthenticatedUserUserProfileRoute: AuthenticatedUserUserProfileRoute,
  AuthenticatedUserUserSettingsRoute: AuthenticatedUserUserSettingsRoute,
}

const AuthenticatedUserUserRouteWithChildren =
  AuthenticatedUserUserRoute._addFileChildren(
    AuthenticatedUserUserRouteChildren,
  )

interface AuthenticatedUserRouteChildren {
  AuthenticatedUserUserRoute: typeof AuthenticatedUserUserRouteWithChildren
}

const AuthenticatedUserRouteChildren: AuthenticatedUserRouteChildren = {
  AuthenticatedUserUserRoute: AuthenticatedUserUserRouteWithChildren,
}

const AuthenticatedUserRouteWithChildren =
  AuthenticatedUserRoute._addFileChildren(AuthenticatedUserRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardActivitiesRoute: typeof AuthenticatedDashboardActivitiesRoute
  AuthenticatedDashboardMembersRoute: typeof AuthenticatedDashboardMembersRoute
  AuthenticatedDashboardSocialRoute: typeof AuthenticatedDashboardSocialRoute
  AuthenticatedUserRoute: typeof AuthenticatedUserRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardClubsCreateRoute: typeof AuthenticatedDashboardClubsCreateRoute
  AuthenticatedFacilitiesComplexesCreateRoute: typeof AuthenticatedFacilitiesComplexesCreateRoute
  AuthenticatedDashboardClubsIndexRoute: typeof AuthenticatedDashboardClubsIndexRoute
  AuthenticatedFacilitiesComplexesIndexRoute: typeof AuthenticatedFacilitiesComplexesIndexRoute
  AuthenticatedFacilitiesRoomsIndexRoute: typeof AuthenticatedFacilitiesRoomsIndexRoute
  AuthenticatedDashboardClubsClubIdEditRoute: typeof AuthenticatedDashboardClubsClubIdEditRoute
  AuthenticatedFacilitiesComplexesComplexIdCreateRoomRoute: typeof AuthenticatedFacilitiesComplexesComplexIdCreateRoomRoute
  AuthenticatedFacilitiesComplexesComplexIdEditRoute: typeof AuthenticatedFacilitiesComplexesComplexIdEditRoute
  AuthenticatedFacilitiesRoomsRoomIdEditRoute: typeof AuthenticatedFacilitiesRoomsRoomIdEditRoute
  AuthenticatedDashboardClubsClubIdIndexRoute: typeof AuthenticatedDashboardClubsClubIdIndexRoute
  AuthenticatedFacilitiesComplexesComplexIdIndexRoute: typeof AuthenticatedFacilitiesComplexesComplexIdIndexRoute
  AuthenticatedFacilitiesRoomsRoomIdIndexRoute: typeof AuthenticatedFacilitiesRoomsRoomIdIndexRoute
  AuthenticatedDashboardClubsClubIdSectionsCreateRoute: typeof AuthenticatedDashboardClubsClubIdSectionsCreateRoute
  AuthenticatedDashboardClubsClubIdCategoriesIndexRoute: typeof AuthenticatedDashboardClubsClubIdCategoriesIndexRoute
  AuthenticatedDashboardClubsClubIdSectionsIndexRoute: typeof AuthenticatedDashboardClubsClubIdSectionsIndexRoute
  AuthenticatedDashboardClubsClubIdSessionsIndexRoute: typeof AuthenticatedDashboardClubsClubIdSessionsIndexRoute
  AuthenticatedDashboardClubsClubIdSectionsSectionIdEditRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdEditRoute
  AuthenticatedDashboardClubsClubIdSectionsSectionIdIndexRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdIndexRoute
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCreateRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCreateRoute
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesIndexRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesIndexRoute
  AuthenticatedDashboardClubsClubIdSectionsSectionIdSessionsIndexRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdSessionsIndexRoute
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdEditRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdEditRoute
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsCreateRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsCreateRoute
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsIndexRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsIndexRoute
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsSessionIdEditRoute: typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsSessionIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardActivitiesRoute: AuthenticatedDashboardActivitiesRoute,
  AuthenticatedDashboardMembersRoute: AuthenticatedDashboardMembersRoute,
  AuthenticatedDashboardSocialRoute: AuthenticatedDashboardSocialRoute,
  AuthenticatedUserRoute: AuthenticatedUserRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardClubsCreateRoute:
    AuthenticatedDashboardClubsCreateRoute,
  AuthenticatedFacilitiesComplexesCreateRoute:
    AuthenticatedFacilitiesComplexesCreateRoute,
  AuthenticatedDashboardClubsIndexRoute: AuthenticatedDashboardClubsIndexRoute,
  AuthenticatedFacilitiesComplexesIndexRoute:
    AuthenticatedFacilitiesComplexesIndexRoute,
  AuthenticatedFacilitiesRoomsIndexRoute:
    AuthenticatedFacilitiesRoomsIndexRoute,
  AuthenticatedDashboardClubsClubIdEditRoute:
    AuthenticatedDashboardClubsClubIdEditRoute,
  AuthenticatedFacilitiesComplexesComplexIdCreateRoomRoute:
    AuthenticatedFacilitiesComplexesComplexIdCreateRoomRoute,
  AuthenticatedFacilitiesComplexesComplexIdEditRoute:
    AuthenticatedFacilitiesComplexesComplexIdEditRoute,
  AuthenticatedFacilitiesRoomsRoomIdEditRoute:
    AuthenticatedFacilitiesRoomsRoomIdEditRoute,
  AuthenticatedDashboardClubsClubIdIndexRoute:
    AuthenticatedDashboardClubsClubIdIndexRoute,
  AuthenticatedFacilitiesComplexesComplexIdIndexRoute:
    AuthenticatedFacilitiesComplexesComplexIdIndexRoute,
  AuthenticatedFacilitiesRoomsRoomIdIndexRoute:
    AuthenticatedFacilitiesRoomsRoomIdIndexRoute,
  AuthenticatedDashboardClubsClubIdSectionsCreateRoute:
    AuthenticatedDashboardClubsClubIdSectionsCreateRoute,
  AuthenticatedDashboardClubsClubIdCategoriesIndexRoute:
    AuthenticatedDashboardClubsClubIdCategoriesIndexRoute,
  AuthenticatedDashboardClubsClubIdSectionsIndexRoute:
    AuthenticatedDashboardClubsClubIdSectionsIndexRoute,
  AuthenticatedDashboardClubsClubIdSessionsIndexRoute:
    AuthenticatedDashboardClubsClubIdSessionsIndexRoute,
  AuthenticatedDashboardClubsClubIdSectionsSectionIdEditRoute:
    AuthenticatedDashboardClubsClubIdSectionsSectionIdEditRoute,
  AuthenticatedDashboardClubsClubIdSectionsSectionIdIndexRoute:
    AuthenticatedDashboardClubsClubIdSectionsSectionIdIndexRoute,
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCreateRoute:
    AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCreateRoute,
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesIndexRoute:
    AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesIndexRoute,
  AuthenticatedDashboardClubsClubIdSectionsSectionIdSessionsIndexRoute:
    AuthenticatedDashboardClubsClubIdSectionsSectionIdSessionsIndexRoute,
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdEditRoute:
    AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdEditRoute,
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsCreateRoute:
    AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsCreateRoute,
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsIndexRoute:
    AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsIndexRoute,
  AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsSessionIdEditRoute:
    AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsSessionIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthVerifyVerifyRouteChildren {
  AuthVerifyVerifyErrorRoute: typeof AuthVerifyVerifyErrorRoute
  AuthVerifyVerifySuccessRoute: typeof AuthVerifyVerifySuccessRoute
}

const AuthVerifyVerifyRouteChildren: AuthVerifyVerifyRouteChildren = {
  AuthVerifyVerifyErrorRoute: AuthVerifyVerifyErrorRoute,
  AuthVerifyVerifySuccessRoute: AuthVerifyVerifySuccessRoute,
}

const AuthVerifyVerifyRouteWithChildren =
  AuthVerifyVerifyRoute._addFileChildren(AuthVerifyVerifyRouteChildren)

interface AuthVerifyRouteChildren {
  AuthVerifyVerifyRoute: typeof AuthVerifyVerifyRouteWithChildren
  AuthVerifyIndexRoute: typeof AuthVerifyIndexRoute
}

const AuthVerifyRouteChildren: AuthVerifyRouteChildren = {
  AuthVerifyVerifyRoute: AuthVerifyVerifyRouteWithChildren,
  AuthVerifyIndexRoute: AuthVerifyIndexRoute,
}

const AuthVerifyRouteWithChildren = AuthVerifyRoute._addFileChildren(
  AuthVerifyRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthAccountCreatedRoute: typeof AuthAccountCreatedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSendVerificationEmailRoute: typeof AuthSendVerificationEmailRoute
  AuthVerifyRoute: typeof AuthVerifyRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRoute,
  AuthAccountCreatedRoute: AuthAccountCreatedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSendVerificationEmailRoute: AuthSendVerificationEmailRoute,
  AuthVerifyRoute: AuthVerifyRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "": typeof AuthenticatedRouteWithChildren
  "/auth": typeof AuthLayoutRoute
  "/auth/account-created": typeof AuthAccountCreatedRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/auth/send-verification-email": typeof AuthSendVerificationEmailRoute
  "/dashboard/activities": typeof AuthenticatedDashboardActivitiesRoute
  "/dashboard/members": typeof AuthenticatedDashboardMembersRoute
  "/dashboard/social": typeof AuthenticatedDashboardSocialRoute
  "/user": typeof AuthenticatedUserUserRouteWithChildren
  "/auth/verify": typeof AuthVerifyVerifyRouteWithChildren
  "/dashboard": typeof AuthenticatedDashboardIndexRoute
  "/auth/verify/": typeof AuthVerifyIndexRoute
  "/dashboard/clubs/create": typeof AuthenticatedDashboardClubsCreateRoute
  "/facilities/complexes/create": typeof AuthenticatedFacilitiesComplexesCreateRoute
  "/user/profile": typeof AuthenticatedUserUserProfileRoute
  "/user/settings": typeof AuthenticatedUserUserSettingsRoute
  "/auth/verify/error": typeof AuthVerifyVerifyErrorRoute
  "/auth/verify/success": typeof AuthVerifyVerifySuccessRoute
  "/dashboard/clubs": typeof AuthenticatedDashboardClubsIndexRoute
  "/facilities/complexes": typeof AuthenticatedFacilitiesComplexesIndexRoute
  "/facilities/rooms": typeof AuthenticatedFacilitiesRoomsIndexRoute
  "/dashboard/clubs/$clubId/edit": typeof AuthenticatedDashboardClubsClubIdEditRoute
  "/facilities/complexes/$complexId/create-room": typeof AuthenticatedFacilitiesComplexesComplexIdCreateRoomRoute
  "/facilities/complexes/$complexId/edit": typeof AuthenticatedFacilitiesComplexesComplexIdEditRoute
  "/facilities/rooms/$roomId/edit": typeof AuthenticatedFacilitiesRoomsRoomIdEditRoute
  "/dashboard/clubs/$clubId": typeof AuthenticatedDashboardClubsClubIdIndexRoute
  "/facilities/complexes/$complexId": typeof AuthenticatedFacilitiesComplexesComplexIdIndexRoute
  "/facilities/rooms/$roomId": typeof AuthenticatedFacilitiesRoomsRoomIdIndexRoute
  "/dashboard/clubs/$clubId/sections/create": typeof AuthenticatedDashboardClubsClubIdSectionsCreateRoute
  "/dashboard/clubs/$clubId/categories": typeof AuthenticatedDashboardClubsClubIdCategoriesIndexRoute
  "/dashboard/clubs/$clubId/sections": typeof AuthenticatedDashboardClubsClubIdSectionsIndexRoute
  "/dashboard/clubs/$clubId/sessions": typeof AuthenticatedDashboardClubsClubIdSessionsIndexRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/edit": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdEditRoute
  "/dashboard/clubs/$clubId/sections/$sectionId": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdIndexRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories/create": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCreateRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesIndexRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/sessions": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdSessionsIndexRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdEditRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsCreateRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsIndexRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsSessionIdEditRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "": typeof AuthenticatedRouteWithChildren
  "/auth": typeof AuthLayoutRoute
  "/auth/account-created": typeof AuthAccountCreatedRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/auth/send-verification-email": typeof AuthSendVerificationEmailRoute
  "/dashboard/activities": typeof AuthenticatedDashboardActivitiesRoute
  "/dashboard/members": typeof AuthenticatedDashboardMembersRoute
  "/dashboard/social": typeof AuthenticatedDashboardSocialRoute
  "/user": typeof AuthenticatedUserUserRouteWithChildren
  "/auth/verify": typeof AuthVerifyIndexRoute
  "/dashboard": typeof AuthenticatedDashboardIndexRoute
  "/dashboard/clubs/create": typeof AuthenticatedDashboardClubsCreateRoute
  "/facilities/complexes/create": typeof AuthenticatedFacilitiesComplexesCreateRoute
  "/user/profile": typeof AuthenticatedUserUserProfileRoute
  "/user/settings": typeof AuthenticatedUserUserSettingsRoute
  "/auth/verify/error": typeof AuthVerifyVerifyErrorRoute
  "/auth/verify/success": typeof AuthVerifyVerifySuccessRoute
  "/dashboard/clubs": typeof AuthenticatedDashboardClubsIndexRoute
  "/facilities/complexes": typeof AuthenticatedFacilitiesComplexesIndexRoute
  "/facilities/rooms": typeof AuthenticatedFacilitiesRoomsIndexRoute
  "/dashboard/clubs/$clubId/edit": typeof AuthenticatedDashboardClubsClubIdEditRoute
  "/facilities/complexes/$complexId/create-room": typeof AuthenticatedFacilitiesComplexesComplexIdCreateRoomRoute
  "/facilities/complexes/$complexId/edit": typeof AuthenticatedFacilitiesComplexesComplexIdEditRoute
  "/facilities/rooms/$roomId/edit": typeof AuthenticatedFacilitiesRoomsRoomIdEditRoute
  "/dashboard/clubs/$clubId": typeof AuthenticatedDashboardClubsClubIdIndexRoute
  "/facilities/complexes/$complexId": typeof AuthenticatedFacilitiesComplexesComplexIdIndexRoute
  "/facilities/rooms/$roomId": typeof AuthenticatedFacilitiesRoomsRoomIdIndexRoute
  "/dashboard/clubs/$clubId/sections/create": typeof AuthenticatedDashboardClubsClubIdSectionsCreateRoute
  "/dashboard/clubs/$clubId/categories": typeof AuthenticatedDashboardClubsClubIdCategoriesIndexRoute
  "/dashboard/clubs/$clubId/sections": typeof AuthenticatedDashboardClubsClubIdSectionsIndexRoute
  "/dashboard/clubs/$clubId/sessions": typeof AuthenticatedDashboardClubsClubIdSessionsIndexRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/edit": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdEditRoute
  "/dashboard/clubs/$clubId/sections/$sectionId": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdIndexRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories/create": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCreateRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesIndexRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/sessions": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdSessionsIndexRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdEditRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsCreateRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsIndexRoute
  "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsSessionIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/auth": typeof AuthRouteWithChildren
  "/auth/_layout": typeof AuthLayoutRoute
  "/auth/account-created": typeof AuthAccountCreatedRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/register": typeof AuthRegisterRoute
  "/auth/reset-password": typeof AuthResetPasswordRoute
  "/auth/send-verification-email": typeof AuthSendVerificationEmailRoute
  "/_authenticated/dashboard/activities": typeof AuthenticatedDashboardActivitiesRoute
  "/_authenticated/dashboard/members": typeof AuthenticatedDashboardMembersRoute
  "/_authenticated/dashboard/social": typeof AuthenticatedDashboardSocialRoute
  "/_authenticated/user": typeof AuthenticatedUserRouteWithChildren
  "/_authenticated/user/_user": typeof AuthenticatedUserUserRouteWithChildren
  "/auth/verify": typeof AuthVerifyRouteWithChildren
  "/auth/verify/_verify": typeof AuthVerifyVerifyRouteWithChildren
  "/_authenticated/dashboard/": typeof AuthenticatedDashboardIndexRoute
  "/auth/verify/": typeof AuthVerifyIndexRoute
  "/_authenticated/dashboard/clubs/create": typeof AuthenticatedDashboardClubsCreateRoute
  "/_authenticated/facilities/complexes/create": typeof AuthenticatedFacilitiesComplexesCreateRoute
  "/_authenticated/user/_user/profile": typeof AuthenticatedUserUserProfileRoute
  "/_authenticated/user/_user/settings": typeof AuthenticatedUserUserSettingsRoute
  "/auth/verify/_verify/error": typeof AuthVerifyVerifyErrorRoute
  "/auth/verify/_verify/success": typeof AuthVerifyVerifySuccessRoute
  "/_authenticated/dashboard/clubs/": typeof AuthenticatedDashboardClubsIndexRoute
  "/_authenticated/facilities/complexes/": typeof AuthenticatedFacilitiesComplexesIndexRoute
  "/_authenticated/facilities/rooms/": typeof AuthenticatedFacilitiesRoomsIndexRoute
  "/_authenticated/dashboard/clubs/$clubId/edit": typeof AuthenticatedDashboardClubsClubIdEditRoute
  "/_authenticated/facilities/complexes/$complexId/create-room": typeof AuthenticatedFacilitiesComplexesComplexIdCreateRoomRoute
  "/_authenticated/facilities/complexes/$complexId/edit": typeof AuthenticatedFacilitiesComplexesComplexIdEditRoute
  "/_authenticated/facilities/rooms/$roomId/edit": typeof AuthenticatedFacilitiesRoomsRoomIdEditRoute
  "/_authenticated/dashboard/clubs/$clubId/": typeof AuthenticatedDashboardClubsClubIdIndexRoute
  "/_authenticated/facilities/complexes/$complexId/": typeof AuthenticatedFacilitiesComplexesComplexIdIndexRoute
  "/_authenticated/facilities/rooms/$roomId/": typeof AuthenticatedFacilitiesRoomsRoomIdIndexRoute
  "/_authenticated/dashboard/clubs/$clubId/sections/create": typeof AuthenticatedDashboardClubsClubIdSectionsCreateRoute
  "/_authenticated/dashboard/clubs/$clubId/categories/": typeof AuthenticatedDashboardClubsClubIdCategoriesIndexRoute
  "/_authenticated/dashboard/clubs/$clubId/sections/": typeof AuthenticatedDashboardClubsClubIdSectionsIndexRoute
  "/_authenticated/dashboard/clubs/$clubId/sessions/": typeof AuthenticatedDashboardClubsClubIdSessionsIndexRoute
  "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/edit": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdEditRoute
  "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdIndexRoute
  "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/create": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCreateRoute
  "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesIndexRoute
  "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/sessions/": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdSessionsIndexRoute
  "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdEditRoute
  "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsCreateRoute
  "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsIndexRoute
  "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit": typeof AuthenticatedDashboardClubsClubIdSectionsSectionIdCategoriesCategoryIdSessionsSessionIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | ""
    | "/auth"
    | "/auth/account-created"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/send-verification-email"
    | "/dashboard/activities"
    | "/dashboard/members"
    | "/dashboard/social"
    | "/user"
    | "/auth/verify"
    | "/dashboard"
    | "/auth/verify/"
    | "/dashboard/clubs/create"
    | "/facilities/complexes/create"
    | "/user/profile"
    | "/user/settings"
    | "/auth/verify/error"
    | "/auth/verify/success"
    | "/dashboard/clubs"
    | "/facilities/complexes"
    | "/facilities/rooms"
    | "/dashboard/clubs/$clubId/edit"
    | "/facilities/complexes/$complexId/create-room"
    | "/facilities/complexes/$complexId/edit"
    | "/facilities/rooms/$roomId/edit"
    | "/dashboard/clubs/$clubId"
    | "/facilities/complexes/$complexId"
    | "/facilities/rooms/$roomId"
    | "/dashboard/clubs/$clubId/sections/create"
    | "/dashboard/clubs/$clubId/categories"
    | "/dashboard/clubs/$clubId/sections"
    | "/dashboard/clubs/$clubId/sessions"
    | "/dashboard/clubs/$clubId/sections/$sectionId/edit"
    | "/dashboard/clubs/$clubId/sections/$sectionId"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories/create"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories"
    | "/dashboard/clubs/$clubId/sections/$sectionId/sessions"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | ""
    | "/auth"
    | "/auth/account-created"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/send-verification-email"
    | "/dashboard/activities"
    | "/dashboard/members"
    | "/dashboard/social"
    | "/user"
    | "/auth/verify"
    | "/dashboard"
    | "/dashboard/clubs/create"
    | "/facilities/complexes/create"
    | "/user/profile"
    | "/user/settings"
    | "/auth/verify/error"
    | "/auth/verify/success"
    | "/dashboard/clubs"
    | "/facilities/complexes"
    | "/facilities/rooms"
    | "/dashboard/clubs/$clubId/edit"
    | "/facilities/complexes/$complexId/create-room"
    | "/facilities/complexes/$complexId/edit"
    | "/facilities/rooms/$roomId/edit"
    | "/dashboard/clubs/$clubId"
    | "/facilities/complexes/$complexId"
    | "/facilities/rooms/$roomId"
    | "/dashboard/clubs/$clubId/sections/create"
    | "/dashboard/clubs/$clubId/categories"
    | "/dashboard/clubs/$clubId/sections"
    | "/dashboard/clubs/$clubId/sessions"
    | "/dashboard/clubs/$clubId/sections/$sectionId/edit"
    | "/dashboard/clubs/$clubId/sections/$sectionId"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories/create"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories"
    | "/dashboard/clubs/$clubId/sections/$sectionId/sessions"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions"
    | "/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/auth"
    | "/auth/_layout"
    | "/auth/account-created"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/send-verification-email"
    | "/_authenticated/dashboard/activities"
    | "/_authenticated/dashboard/members"
    | "/_authenticated/dashboard/social"
    | "/_authenticated/user"
    | "/_authenticated/user/_user"
    | "/auth/verify"
    | "/auth/verify/_verify"
    | "/_authenticated/dashboard/"
    | "/auth/verify/"
    | "/_authenticated/dashboard/clubs/create"
    | "/_authenticated/facilities/complexes/create"
    | "/_authenticated/user/_user/profile"
    | "/_authenticated/user/_user/settings"
    | "/auth/verify/_verify/error"
    | "/auth/verify/_verify/success"
    | "/_authenticated/dashboard/clubs/"
    | "/_authenticated/facilities/complexes/"
    | "/_authenticated/facilities/rooms/"
    | "/_authenticated/dashboard/clubs/$clubId/edit"
    | "/_authenticated/facilities/complexes/$complexId/create-room"
    | "/_authenticated/facilities/complexes/$complexId/edit"
    | "/_authenticated/facilities/rooms/$roomId/edit"
    | "/_authenticated/dashboard/clubs/$clubId/"
    | "/_authenticated/facilities/complexes/$complexId/"
    | "/_authenticated/facilities/rooms/$roomId/"
    | "/_authenticated/dashboard/clubs/$clubId/sections/create"
    | "/_authenticated/dashboard/clubs/$clubId/categories/"
    | "/_authenticated/dashboard/clubs/$clubId/sections/"
    | "/_authenticated/dashboard/clubs/$clubId/sessions/"
    | "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/edit"
    | "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/"
    | "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/create"
    | "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/"
    | "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/sessions/"
    | "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit"
    | "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create"
    | "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/"
    | "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard/activities",
        "/_authenticated/dashboard/members",
        "/_authenticated/dashboard/social",
        "/_authenticated/user",
        "/_authenticated/dashboard/",
        "/_authenticated/dashboard/clubs/create",
        "/_authenticated/facilities/complexes/create",
        "/_authenticated/dashboard/clubs/",
        "/_authenticated/facilities/complexes/",
        "/_authenticated/facilities/rooms/",
        "/_authenticated/dashboard/clubs/$clubId/edit",
        "/_authenticated/facilities/complexes/$complexId/create-room",
        "/_authenticated/facilities/complexes/$complexId/edit",
        "/_authenticated/facilities/rooms/$roomId/edit",
        "/_authenticated/dashboard/clubs/$clubId/",
        "/_authenticated/facilities/complexes/$complexId/",
        "/_authenticated/facilities/rooms/$roomId/",
        "/_authenticated/dashboard/clubs/$clubId/sections/create",
        "/_authenticated/dashboard/clubs/$clubId/categories/",
        "/_authenticated/dashboard/clubs/$clubId/sections/",
        "/_authenticated/dashboard/clubs/$clubId/sessions/",
        "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/edit",
        "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/",
        "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/create",
        "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/",
        "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/sessions/",
        "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit",
        "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create",
        "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/",
        "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_layout",
        "/auth/account-created",
        "/auth/forgot-password",
        "/auth/login",
        "/auth/register",
        "/auth/reset-password",
        "/auth/send-verification-email",
        "/auth/verify"
      ]
    },
    "/auth/_layout": {
      "filePath": "auth/_layout.tsx",
      "parent": "/auth"
    },
    "/auth/account-created": {
      "filePath": "auth/account-created.tsx",
      "parent": "/auth"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx",
      "parent": "/auth"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx",
      "parent": "/auth"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.tsx",
      "parent": "/auth"
    },
    "/auth/send-verification-email": {
      "filePath": "auth/send-verification-email.tsx",
      "parent": "/auth"
    },
    "/_authenticated/dashboard/activities": {
      "filePath": "_authenticated/dashboard/activities.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/members": {
      "filePath": "_authenticated/dashboard/members.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/social": {
      "filePath": "_authenticated/dashboard/social.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/user": {
      "filePath": "_authenticated/user",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/user/_user"
      ]
    },
    "/_authenticated/user/_user": {
      "filePath": "_authenticated/user/_user.tsx",
      "parent": "/_authenticated/user",
      "children": [
        "/_authenticated/user/_user/profile",
        "/_authenticated/user/_user/settings"
      ]
    },
    "/auth/verify": {
      "filePath": "auth/verify",
      "parent": "/auth",
      "children": [
        "/auth/verify/_verify",
        "/auth/verify/"
      ]
    },
    "/auth/verify/_verify": {
      "filePath": "auth/verify/_verify.tsx",
      "parent": "/auth/verify",
      "children": [
        "/auth/verify/_verify/error",
        "/auth/verify/_verify/success"
      ]
    },
    "/_authenticated/dashboard/": {
      "filePath": "_authenticated/dashboard/index.tsx",
      "parent": "/_authenticated"
    },
    "/auth/verify/": {
      "filePath": "auth/verify/index.tsx",
      "parent": "/auth/verify"
    },
    "/_authenticated/dashboard/clubs/create": {
      "filePath": "_authenticated/dashboard/clubs/create.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/facilities/complexes/create": {
      "filePath": "_authenticated/facilities/complexes/create.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/user/_user/profile": {
      "filePath": "_authenticated/user/_user.profile.tsx",
      "parent": "/_authenticated/user/_user"
    },
    "/_authenticated/user/_user/settings": {
      "filePath": "_authenticated/user/_user.settings.tsx",
      "parent": "/_authenticated/user/_user"
    },
    "/auth/verify/_verify/error": {
      "filePath": "auth/verify/_verify.error.tsx",
      "parent": "/auth/verify/_verify"
    },
    "/auth/verify/_verify/success": {
      "filePath": "auth/verify/_verify.success.tsx",
      "parent": "/auth/verify/_verify"
    },
    "/_authenticated/dashboard/clubs/": {
      "filePath": "_authenticated/dashboard/clubs/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/facilities/complexes/": {
      "filePath": "_authenticated/facilities/complexes/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/facilities/rooms/": {
      "filePath": "_authenticated/facilities/rooms/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/edit": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/facilities/complexes/$complexId/create-room": {
      "filePath": "_authenticated/facilities/complexes/$complexId.create-room.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/facilities/complexes/$complexId/edit": {
      "filePath": "_authenticated/facilities/complexes/$complexId.edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/facilities/rooms/$roomId/edit": {
      "filePath": "_authenticated/facilities/rooms/$roomId.edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/facilities/complexes/$complexId/": {
      "filePath": "_authenticated/facilities/complexes/$complexId/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/facilities/rooms/$roomId/": {
      "filePath": "_authenticated/facilities/rooms/$roomId/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sections/create": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sections/create.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/categories/": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/categories/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sections/": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sections/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sessions/": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sessions/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/edit": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sections/$sectionId/edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sections/$sectionId/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/create": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/create.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/sessions/": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sections/$sectionId/sessions/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/create.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit": {
      "filePath": "_authenticated/dashboard/clubs/$clubId/sections/$sectionId/categories/$categoryId/sessions/$sessionId/edit.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
