services:
  nginx:
    image: nginx:1.27.5-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

  client:
    image: node:22.15.0-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    expose:
      - 5173
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    
  server:
    image: node:22.15.0-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    expose:
      - 3000
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - minio

  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data/minio
    command: 'minio server /data/minio --console-address ":9001"'
    environment:
      - MINIO_ROOT_USER=admin # access key id
      - MINIO_ROOT_PASSWORD=password # secret access key
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=asp_db


volumes:
  postgres-data:
  minio-data:
