services:
  nginx:
    image: nginx:1.27.5-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

  client:
    image: node:22.15.0-alpine
    working_dir: /app
    command: sh -c "npm run dev -- --host"
    expose:
      - 5173
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules:ro
      - ./client/node_modules/.vite:/app/node_modules/.vite
      - ./client/node_modules/.vite-temp:/app/node_modules/.vite-temp
    environment:
      - NODE_ENV=development
    
  server:
    image: node:22.15.0-alpine
    working_dir: /app
    command: sh -c "npm run dev"
    expose:
      - 3000
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules:ro
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      # - mongo
      - minio

  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data/minio
    command: 'minio server /data/minio --console-address ":9001"'
    environment:
      - MINIO_ROOT_USER=admin # access key id
      - MINIO_ROOT_PASSWORD=password # secret access key
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  postgres:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=asp_db
    
  # mongo:
  #   image: mongo:8.0.9
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=password
  #     - MONGO_INITDB_DATABASE=asp_mongo

volumes:
  mongo-data:
  postgres-data:
  minio-data:
