services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: mchegdali/asphub-client:latest
    environment:
      - VIRTUAL_HOST=mchegdali.cloud
      - VIRTUAL_PATH=/
    networks:
      - proxy

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: mchegdali/asphub-server:latest
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - MONGO_URI=${MONGO_URI}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - CLIENT_URL=mchegdali.cloud
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - VIRTUAL_HOST=mchegdali.cloud
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/api
    depends_on:
      - postgres
      - minio
    networks:
      - proxy

  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    volumes:
      - minio-data:/data/minio
    command: 'minio server /data/minio --console-address ":9001"'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1

  postgres:
    image: postgres:17.5-alpine
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    configs:
      - source: postgres-config
        target: /etc/postgresql.conf
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    volumes:
     - postgres-data:/var/lib/postgresql/data
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728 # 128*2^20 bytes = 128Mb
    deploy:
      resources:
        reservations:
          cpus: '0.50'
          memory: '1024M'
        limits:
          cpus: '1.00'
          memory: '2048M'

configs:
  postgres-config:
    file: config/postgresql.conf

volumes:
  postgres-data:
  minio-data:

networks:
  proxy:
    external: true
