services:
  client:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    
  server:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=asp_db
      - MONGO_URI=mongodb://root:password@mongo:27017/asp_mongo?authSource=admin
    depends_on:
      - postgres
      - mongo
    
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=asp_db
    
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=asp_mongo

volumes:
  mongo-data:
  postgres-data: