services:
  client:
    image: node:22.15.0-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    
  server:
    image: node:22.15.0-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/asp_db
      - MONGO_URI=mongodb://root:password@mongo:27017/asp_mongo?authSource=admin
      - BETTER_AUTH_SECRET=secret
      - BETTER_AUTH_URL=http://localhost:5173
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - postgres
      - mongo
    
  postgres:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=asp_db
    
  mongo:
    image: mongo:8.0.9
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=asp_mongo

volumes:
  mongo-data:
  postgres-data: