name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  ORGANIZATION: llamasscripters
  CLIENT_IMAGE: ghcr.io/llamasscripters/asphub-client
  SERVER_IMAGE: ghcr.io/llamasscripters/asphub-server
  STACK_NAME: asphub
  NODE_VERSION: "22.15.0"

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: |
            ./package-lock.json
            ./client/package-lock.json
            ./server/package-lock.json

      - name: Install root dependencies
        run: npm install

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      # - name: Run lint checks
      #   run: npm run lint

      # - name: Run client typecheck
      #   working-directory: ./client
      #   run: npm run typecheck

      # - name: Run server typecheck
      #   working-directory: ./server
      #   run: npm run typecheck

      # - name: Run client tests
      #   working-directory: ./client
      #   run: |
      #     npm run test:e2e

      # - name: Run server tests
      #   working-directory: ./server
      #   run: npm run test

  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: quality-checks
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.ORGANIZATION }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push client image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          target: production
          push: true
          tags: ${{ env.CLIENT_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Build and push server image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          target: production
          push: true
          tags: ${{ env.SERVER_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up docker context over SSH authentication
        uses: amirmarmul/docker-context-ssh-action@90312071047da58fda503391fd98d2890b042bb5
        with:
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          context-name: production
          context-use: true

      - name: Update stack services
        run: |
          # Use commit SHA for deterministic deployments
          CLIENT_TAG="${{ env.CLIENT_IMAGE }}:${{ github.sha }}"
          SERVER_TAG="${{ env.SERVER_IMAGE }}:${{ github.sha }}"

          echo "🚀 Deployment summary:"
          echo "  Trigger: ${{ github.ref_type }}"
          echo "  Commit SHA: ${{ github.sha }}"
          echo "  Client image: ${CLIENT_TAG}"
          echo "  Server image: ${SERVER_TAG}"

          echo "📦 Updating client service..."
          docker service update \
            --image "${CLIENT_TAG}" \
            ${{ env.STACK_NAME }}_client

          echo "📦 Updating server service..."
          docker service update \
            --image "${SERVER_TAG}" \
            ${{ env.STACK_NAME }}_server

      - name: Verify deployment
        run: |
          # Use reusable deployment verification script
          scripts/deployment/verify-deployment.sh \
            --stack-name="${{ env.STACK_NAME }}" \
            --services="client,server" \
            --timeout=300 \
            --interval=10

      - name: Cleanup Docker context
        if: always()
        run: |
          docker context use default
          docker context rm production || true
